# Generated by Django 5.0.2 on 2024-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='payment_id'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank='True', max_length=300, null='True', verbose_name='payment_link'),
            preserve_default='True',
        ),
    ]
