# Generated by Django 5.0.2 on 2024-02-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='', verbose_name='Course Preview')),
                ('description', models.TextField(verbose_name='Course Description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lesson Name')),
                ('description', models.TextField(verbose_name='Lesson Description')),
                ('preview', models.ImageField(blank='True', null='True', upload_to='', verbose_name='Lesson Preview')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='lessons.course')),
            ],
        ),
    ]
